export enum Property {
    ADDRESS = 'address',
    ADDRESS1 = 'address1',
    ADDRESS2 = 'address2',
    ADDRESSES = 'addresses',
    ADMIN = 'admin',

    BODY = 'body',
    BRANCH = 'branch',
    BRANCH_TYPE = 'branchType',
    BRANCH_ID = 'branchId',
    BRAND_ID = 'brandId',
    BREAK_POINT = 'breakPoint',

    CATEGORY = 'category',
    CANCELLATION_NOTES = 'cancellationNotes',
    CART = 'cart',
    CART_ITEMS = 'cartItems',
    CATEGORY_ID = 'categoryId',
    CITY = 'city',
    COMPANY = 'company',
    COMPANY_ID = 'companyId',
    CONFIRM_NEW_PASSWORD = 'confirmNewPassword',
    CONFIRM_PASSWORD = 'confirmPassword',
    COST = 'cost',
    CUSTOMER_ID = 'customerId',
    CUSTOMER_BRANCH_ID = 'customerBranchId',

    DESCRIPTION = 'description',
    DELETED_PERMISSIONS = 'deletedPermissions',
    DELIVERY_NOTE = 'deliveryNote',
    DELIVERY_ADDRESS_ID = 'deliveryAddressId',
    DELETED_IMAGES = 'deletedImages',
    DISTRICT = 'district',

    EMAIL = 'email',
    ENABLED_FROM = 'enabledFrom',
    ENABLED_TO = 'enabledTo',

    FIRST_NAME = 'firstName',
    FCM_TOKEN = 'fcmToken',

    ID = 'id',
    IS_DEFAULT = 'isDefault',
    IS_ACTIVE = 'isActive',
    INVENTORY_ID = 'inventoryId',
    IN_OUT = 'inOut',

    LAST_NAME = 'lastName',
    LONGITUDE = 'longitude',
    LATITUDE = 'latitude',
    LONG_DESCRIPTION = 'longDescription',

    MANAGE_PRODUCT_TRACKING_ID = 'manageProductTrackingId',
    METADATA = 'metadata',

    NAME = 'name',
    NEW_PASSWORD = 'newPassword',
    NAME_OF_REPRESENTATIVE = 'nameOfRepresentative',

    ORDER = 'order',
    ORDER_ITEMS = 'orderItems',
    ORDER_STATUS = 'orderStatus',

    PASSWORD = 'password',
    PHONE_NUMBER = 'phoneNumber',
    PERMISSION_ID = 'permissionId',
    PERMISSIONS = 'permissions',
    PERMISSION = 'permission',
    PARENT_ID = 'parentId',
    PRODUCT_CATEGORY = 'product',
    PRODUCT = 'product',
    PRODUCT_IDS = 'productsIds',
    PRODUCTS_COST = 'productsCost',
    PRICE = 'price',
    PAYMENT_METHOD = 'paymentMethod',
    PACK_SIZE = 'packSize',
    PERIOD_OF_SUBSCRIPTION = 'periodOfSubscription',
    PAYMENT_STATUS = 'paymentStatus',

    QUANTITY = 'quantity',
    QUANTITIES = 'quantities',
    QUANTITY_PRICE = 'quantityPrice',

    ROLE_ID = 'roleId',
    ROLES = 'roles',
    ROLE = 'role',
    REWARD_POINTS = 'rewardPoints',

    SHIPPING_COST = 'shippingCost',
    SUB_TOTAL = 'subtotal',
    SHOW_ON_DASHBOARD = 'showOnDashboard',
    SORT_ORDER = 'sortOrder',
    SELLER_ID = 'sellerId',
    SELLER_BRANCH_ID = 'sellerBranchId',
    SHORT_DESCRIPTION = 'shortDescription',
    SKU = 'sku',
    STATUS = 'status',
    SUBSCRIPTION_ID = 'subscriptionId',
    SUBSCRIPTION_PLAN_ID = 'subscriptionPlanId',

    TOKEN = 'token',
    TITLE = 'title',
    TITLE_OF_REPRESENTATIVE = 'titleOfRepresentative',
    TYPE = 'type',

    USER = 'user',
    SELLER = 'seller',
    USER_ID = 'userId',

    VAT_NUMBER = 'vatNumber',

    ZIP_CODE = 'zipCode',
}
