export enum ValidateErrors {
    EXIST = 'validation.Exist',
    FILE = 'validation.File',
    IS_ARRAY = 'validation.IsArray',
    IS_BOOLEAN = 'validation.IsBoolean',
    IS_DATE_STRING = 'validation.IsDateString',
    IS_EMAIL = 'validation.IsEmail',
    IS_ENUM = 'validation.IsEnum',
    IS_MATCH = 'validation.IsMatch',
    IS_MIME_TYPE = 'validation.IsMimeType',
    IS_NOT_EMPTY = 'validation.IsNotEmpty',
    IS_NOT_EMPTY_OBJECT = 'validation.IsNotEmptyObject',
    IS_NUMBER = 'validation.IsNumber',
    IS_NUMBER_STRING = 'validation.IsNumberString',
    IS_OBJECT = 'validation.IsObject',
    IS_STRING = 'validation.IsString',
    IS_UUID = 'validation.IsUUID',
    IS_UUID_ARRAY = 'validation.IsUUIDArray',
    LENGTH = 'validation.Length',
    MATCHES = 'validation.Matches',
    MAX = 'validation.Max',
    MAX_LENGTH = 'validation.MaxLength',
    MIN = 'validation.Min',
    MIN_LENGTH = 'validation.MinLength',
    UNIQUE = 'validation.Unique',
    LENGTH_MIN = 'validation.LengthMin',
    LENGTH_MAX = 'validation.LengthMax',
}
